name: private-package-pr-orchestration

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the main branch
  pull_request:
    paths:
    - 'python_packages/**'
    - '.github/workflows/private-package-pr.yml'

env:
  AWS_REGION: eu-west-1
  AWS_ACCOUNT_ID: 613963413230 
  PR_ROLE: oidc_codeartifact_ro 

permissions:
  id-token: write
  contents: read   
  pull-requests: write

jobs:
  private-python-package-pipeline:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Get Current Pull Request
        uses: 8BitJonny/gh-get-current-pr@1.0.1
        id: pr
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          filterOutClosed: true
      
      - id: file_changes
        name: File Changes
        uses: trilom/file-changes-action@v1.2.3
        with:
          prNumber: ${{ steps.pr.outputs.number }}
          pushBefore: ''
          pushAfter: ''
        
      - name: Ouput File Changes
        run: echo '${{ steps.file_changes.outputs.files }}'