name: private-package-build-orchestration


# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: 
      - main
    paths:
      - 'python_packages/**'
    
permissions:
  id-token: write
  contents: read   
  pull-requests: write

jobs:
  determine-changes:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
          files: python_packages/**
          json: "true"
          dir_names: "true"
          dir_names_max_depth: 2
      - name: Set matrix for next job
        id: set-matrix
        run: echo "matrix={\"dir_names\":${{ steps.changed-files.outputs.all_changed_files }}}" >> "$GITHUB_OUTPUT"
  
  # Cannot pass in env variables in job.job_id.with. .. env not available https://github.com/actions/toolkit/issues/931 - docu here: https://docs.github.com/en/actions/learn-github-actions/contexts#context-availability 
  build-packages:
    needs: [ determine-changes ]
    strategy:
      matrix: ${{ fromJSON(needs.determine-changes.outputs.matrix) }}
    uses: ./.github/workflows/private-package-main-workflow.yml # https://github.blog/changelog/2022-01-25-github-actions-reusable-workflows-can-be-referenced-locally/
    with:
        aws_region: eu-west-1
        aws_account_id: 994911977949    
        aws_role: oidc_rw
        working_directory: ${{ matrix.dir_names }}
        python_version: '3.9'
  
  post-message:
    runs-on: ubuntu-latest
    environment: main
    needs: [build-packages]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Microsoft Teams Notification
        uses: skitionek/notify-microsoft-teams@master
        if: always()
        with:
          webhook_url: ${{ secrets.TEAMS_WEBHOOK_URL }}
          needs: ${{ toJson(needs) }}
          job: ${{ toJson(job) }}
          steps: ${{ toJson(steps) }}


