name: private-package-pr-orchestration

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the main branch
  pull_request:
    paths:
    - 'python_packages/**'
    - '.github/workflows/private-package-pr.yml'

env:
  AWS_REGION: eu-west-1
  AWS_ACCOUNT_ID: 613963413230 
  PR_ROLE: oidc_codeartifact_ro 

permissions:
  id-token: write
  contents: read   
  pull-requests: write

jobs:
  determine-changes:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    outputs:
      changed-dirs: ${{ steps.changed-files.outputs.all_changed_files }}
      matrix2: ${{ steps.matrix2.outputs.matrix2 }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
          files: python_packages/**
          separator: ","
          dir_names: "true"
          dir_names_max_depth: 2
      - name: List all changed files
        id: matrix2
        run: |
          input=${{ steps.changed-files.outputs.all_changed_files }}
          array="$(echo $input | sed 's/\,/\\"\,\\"/g')"
          echo $array
          matrix2={\"target\":[\"${array}\"]}
          echo $matrix2 >> $GITHUB_OUTPUT
          echo $matrix2
          echo "matrix={\"target\":[\"python_packages/data-testing\",\"python_packages/data-validation-helpers\"]}"
 
      # - name: output matrix
      #   id: matrix 
      #   run: |
      #     echo ${{ steps.changed-files.outputs.all_changed_files }}
      #     arr=(${{ steps.changed-files.outputs.all_changed_files }})
      #     echo $arr
      #     echo "matrix={\"target\":[\"python_packages/data-testing\",\"python_packages/data-validation-helpers\"]}" >> $GITHUB_OUTPUT
 
      
  # build-packages:
  #   needs: [ determine-changes ]
  #   strategy:
  #     matrix: ${{ fromJSON(needs.determine-changes.outputs.matrix2) }}
  #   uses: ./.github/workflows/private-package-pr-workflow.yml # https://github.blog/changelog/2022-01-25-github-actions-reusable-workflows-can-be-referenced-locally/
  #   with:
  #       aws_region: eu-west-1
  #       aws_account_id: 613963413230    
  #       aws_role: oidc_codeartifact_ro
  #       working_directory: ${{ matrix.target }}
  #       python_version: '3.9'