name: private-package-pr

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      AWS_REGION:
        required: true
        type: string
      AWS_ACCOUNT_ID:
        required: true
        type: string
      AWS_ROLE:
        required: true
        type: string
      working_directory:
        required: true
        type: string
#   # Triggers the workflow on push events but only for the main branch
#   pull_request:
#     paths:
#     - 'python_packages/**'
#     - '.github/workflows/private-package-pr.yml'

permissions:
  id-token: write
  contents: read   
  pull-requests: write

jobs:
  private-python-package-pipeline:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Configure AWS credentials for main branch role
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::${{ inputs.AWS_ACCOUNT_ID }}:role/${{ inputs.AWS_ROLE }}
          role-session-name: package-to-codeartifact
          aws-region: ${{ inputs.AWS_REGION }}
      - name: Install dependencies
        working-directory: ${{ inputs.working_directory }}
        run: |
          aws codeartifact login --tool pip --domain pltest-artifact --repository pltest-pip-store
          pip install pytest pytest-cov
          pip install -r requirements.txt
      - name: Build coverage file
        working-directory: ${{ inputs.working_directory }}
        run: |
          pytest --junitxml=pytest.xml --cov-report=term-missing --cov=src tests/ | tee pytest-coverage.txt
      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@v1.1.37
        with:
          pytest-coverage-path: ./${{ inputs.working_directory }}/pytest-coverage.txt
          junitxml-path: ./${{ inputs.working_directory }}/pytest.xml
