name: private-package-pr-orchestration

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the main branch
  pull_request:
    paths:
    - 'python_packages/**'
    - '.github/workflows/private-package-pr.yml'

env:
  AWS_REGION: eu-west-1
  AWS_ACCOUNT_ID: 613963413230 
  PR_ROLE: oidc_codeartifact_ro 

permissions:
  id-token: write
  contents: read   
  pull-requests: write

jobs:
  private-python-package-pipeline:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
          path: python_packages
          dir_names: "true"
      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done