name: terraform-pipeline-main

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [ main ]
    
env:
  AWS_REGION: eu-west-1
  AWS_ACCOUNT_ID: 613963413230 
  MAIN_ROLE: oidc_rw

permissions:
  id-token: write
  contents: read   
  pull-requests: write

jobs:
  terraform-pipeline:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials for main branch role
        uses: aws-actions/configure-aws-credentials@v1-node16
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.MAIN_ROLE }}
          role-session-name: github-demo
          aws-region: ${{ env.AWS_REGION }}
      - name: Terraform Init
        id: init
        run: terraform -chdir=terraform init
      - name: Terraform Validate
        id: validate
        run: terraform -chdir=terraform validate -no-color
      - name: Terraform Apply
        id: apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform -chdir=terraform apply -auto-approve