name: tfchecks-pr-commenter
on:
  pull_request:
    paths:
    - 'terraform/**'
    - '.github/workflows/terraform-pr-checks.yml'

env:
  AWS_REGION: eu-west-1
  AWS_ACCOUNT_ID: 613963413230
  PR_ROLE: oidc_ro

jobs:
  tfsec:
    name: tfsec PR commenter
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Clone repo
        uses: actions/checkout@v3
      - name: tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@v1.2.0
        with:
          github_token: ${{ github.token }}
          working_directory: './terraform'
  tflint:
    name: tflint
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      pull-requests: write
    steps:
      - name: Clone repo
        uses: actions/checkout@v3 
      - name: Cache tflint plugin dir
        uses: actions/cache@v3
        with:
          path: ~/.tflint.d/plugins
          key: ubuntu-latest-tflint-${{ hashFiles('.tflint.hcl') }}
      - uses: terraform-linters/setup-tflint@v3
        name: Setup TFLint
        with:
          tflint_version: latest
      # - name: Configure AWS credentials for PR role
      #   uses: aws-actions/configure-aws-credentials@v1-node16
      #   if: github.event_name == 'pull_request'
      #   with:
      #     role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.PR_ROLE }}
      #     role-session-name: github-demo
      #     aws-region: ${{ env.AWS_REGION }} 
      # - name: Terraform Init
      #   id: init
      #   run: terraform -chdir=terraform init
      - name: Show version
        working-directory: terraform
        run: tflint --version
      - name: Init TFLint
        working-directory: terraform
        run: tflint --init
      - name: Run TFLint
        working-directory: terraform
        run: tflint -f compact